language: node_js
addons:
  sauce_connect: true
  hosts:
  - popup-tools.dev
node_js:
- 6
cache:
  directories:
  - node_modules
before_script:
- npm run build
- node test/express/app.js &
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: ikerin@gmail.com
  skip_cleanup: true
  api_key:
    secure: T5r3EVFbDcbxIQi7zGPKSfbdFuIiYpRxwtYwJlhQYfYmzySBMQOnuUm2nDEq9agMGsibxt8u8C9IJaTzYIRs/wXlwMksnNGx+qCxqC5GdpObRY8vtWAdZ17JYSGkCLTci2d/8kU59F6hM6q/t9AzW+gtY0Cvh/BWmrf4Ph90yGselfehLzAdbFDbj+ECgxtUY+oM0gDLh54PhTViyizrQ2KBMropiD6fXJjAJyfFUzIdgCvhmlLLTyHuQ9pjqZ55QCnR9rqah/LtoMvxl0VOv7C7rcaWJN7EXH5zjHnxv7wBcvzQXP9aslsSYBYq+OvtlVp1Z36HAIOXQl9zUWRawSj5ElNBCJ/Ed0yHZbNM/kWY+l2DQx7xYVlr8//AL7MYIuG6N6LVUP47wO2WzCnfxh0qYK0R1tvAHe8KAvd0lAMM20W5e6Pe56yH1DvVpWl65MsiNOCKw/+cj2KnaWf5xrK+Hzl25xGbIkTG/kwBv7Z2Oe9Xv14WeXJy7b7Hm+KP9csKLXPb7GwSG/BOr9Kaq9h2onw13P24jjGRg2CEbcd0Qnqp6pYVksNQaMSA9SPkVi7fzJtjd2CNdt4bwoWBATg7l2230jEQB7NV08K3+MNhghJb99cxQw7+D6ZfZIe0qlcPhK76dXLMJ7q6oOH/TdL43G2Ral1s6RG/NMwyGVo=
  on:
    tags: true
    repo: enhancv/popup-tools
